codeunit 50011 MyReportTest
{
    Subtype = Test;

    var
        Assert: Codeunit "Library Assert";

    [Test]
    [HandlerFunctions('Top10RequestPageHandler')]
    procedure TestTop10CustomersReport()
    begin
        REPORT.Run(REPORT::"Customer - Top 10 List", true, false);
    end;

    [RequestPageHandler]
    procedure Top10RequestPageHandler(var Top10RequestPage: TestRequestPage "Customer - Top 10 List")
    begin
        Top10RequestPage.Customer.SetFilter(Top10RequestPage.Customer."No.", 'TEST*');
    end;

    [ReportHandler]
    procedure Top10ReportHandler(var CustomerTop10List: Report "Customer - Top 10 List")
    var
        TempCustomerAmount: Record "Customer Amount" temporary;
    begin
        if TempCustomerAmount.FindFirst() then
            Assert.IsTrue(TempCustomerAmount."Customer No." <> '', 'Report did not generate any customer data.')
        else
            Error('No data generated by the report.');
    end;


}
